### ISSUE TITLE
ConfigMap not handled

### ISSUE THREAD

**Issue by nabuskey** [nimakaviani/managed-delivery-k8s-plugin#50]
https://github.com/nimakaviani/managed-delivery-k8s-plugin/blob/9e3da75ef83cafcb0e639f1eb4ccf598be183177/k8s-plugin/src/main/kotlin/com/amazon/spinnaker/keel/k8s/resolver/K8sResourceHandler.kt#L62

```
2021-06-01 18:33:49.428 ERROR 1 --- [atcher-worker-7] c.n.s.keel.actuation.ResourceActuator    : Resource check for k8s:resource:deploy-steven-default-con
figmap-keel-cm failed

java.lang.NullPointerException: null cannot be cast to non-null type kotlin.collections.MutableMap<kotlin.String, kotlin.Any?>
        at com.amazon.spinnaker.keel.k8s.resolver.K8sResourceHandler.upsert(K8sResourceHandler.kt:62) ~[na:na]
        at com.netflix.spinnaker.keel.api.plugins.ResourceHandler.create(ResourceHandler.kt:137) ~[keel-api.jar:na]
        at com.netflix.spinnaker.keel.actuation.ResourceActuator.create(ResourceActuator.kt:413) ~[keel-core.jar:na]
        at com.netflix.spinnaker.keel.actuation.ResourceActuator$checkResource$2.invokeSuspend(ResourceActuator.kt:159) ~[keel-core.jar:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
        at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:113) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46) ~[kotlin-stdlib-1.4.32.jar:1.4.32-release-371 (1.4.32)]
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ~[kotlinx-coroutines-core-jvm-1.4.3.jar:na]

```

```
apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: 2016-02-18T18:52:05Z
  name: game-config
  namespace: default
  resourceVersion: "516"
  uid: b4952dc3-d670-11e5-8cd0-68f728db1985
data:
  game.properties: |
    enemies=aliens
    lives=3
    enemies.cheat=true
    enemies.cheat.level=noGoodRotten
    secret.code.passphrase=UUDDLRLRBABAS
    secret.code.allowed=true
    secret.code.lives=30    
  ui.properties: |
    color.good=purple
    color.bad=yellow
    allow.textmode=true
    how.nice.to.look=fairlyNice
```

**Comment by nimakaviani** [comment]
ah it only looks for `spec` and not data probably. should be an easy fix.
